In [1]:
# Import required libraires
import pandas as pd

# Set display options for pandas data frames
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.width', 1000)        # Set display width to a high value

# Data Source [World Bank](https://data.worldbank.org/country/sweden)

In [2]:
# Load the datasets
file1_path = 'API_BN.CAB.XOKA.GD.ZS_DS2_en_csv_v2_2788804/API_BN.CAB.XOKA.GD.ZS_DS2_en_csv_v2_2788804.csv'  # Current account balance (% of GDP)
file2_path = 'API_FP.CPI.TOTL.ZG_DS2_en_csv_v2_2789055/API_FP.CPI.TOTL.ZG_DS2_en_csv_v2_2789055.csv'  # Inflation, consumer prices (annual %)
file3_path = 'API_NY.GDP.MKTP.CD_DS2_en_csv_v2_2788787/API_NY.GDP.MKTP.CD_DS2_en_csv_v2_2788787.csv'  # GDP (current US$)
file4_path = 'API_SL.UEM.TOTL.NE.ZS_DS2_en_csv_v2_2817174/API_SL.UEM.TOTL.NE.ZS_DS2_en_csv_v2_2817174.csv'  # Unemployment, total (% of total labor force)

data1 = pd.read_csv(file1_path, skiprows=4)
data2 = pd.read_csv(file2_path, skiprows=4)
data3 = pd.read_csv(file3_path, skiprows=4)
data4 = pd.read_csv(file4_path, skiprows=4)

In [3]:
data1.head()

                  Country Name Country Code                      Indicator Name     Indicator Code  1960  1961  1962  1963  1964  1965  1966  1967  1968  1969  1970  1971  1972  1973  1974  1975  1976  1977  1978  1979  1980  1981  1982  1983  1984  1985      1986      1987      1988      1989       1990       1991      1992       1993      1994      1995       1996       1997       1998       1999       2000       2001       2002      2003       2004       2005       2006       2007      2008       2009       2010       2011       2012       2013       2014       2015       2016       2017       2018       2019       2020       2021       2022     2023  Unnamed: 68
0                        Aruba          ABW  Current account balance (% of GDP)  BN.CAB.XOKA.GD.ZS   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN -4.600551 -4.627721 -7.425094 -6.714859 -20.679328 -24.023062  4.568765   3.852501  6.506726 -0.021151  -5.008097 -12.782640  -1.127139 -25.277886  11.056872  16.280874 -17.343452 -8.099023  12.013685   4.447573  12.574211   9.645360  0.003930   6.722391 -18.752537  -9.877656   3.473451 -11.813206  -4.658577   3.994142   4.731778   1.119795  -0.591367   2.497110 -12.366826   2.554056   6.504226      NaN          NaN
1  Africa Eastern and Southern          AFE  Current account balance (% of GDP)  BN.CAB.XOKA.GD.ZS   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN       NaN       NaN       NaN        NaN        NaN       NaN        NaN       NaN       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN       NaN        NaN        NaN        NaN        NaN       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN      NaN          NaN
2                  Afghanistan          AFG  Current account balance (% of GDP)  BN.CAB.XOKA.GD.ZS   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN       NaN       NaN       NaN        NaN        NaN       NaN        NaN       NaN       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN       NaN        NaN        NaN        NaN        NaN -2.357990   2.236019  -3.643314 -12.619538 -25.870681 -25.290059 -15.772420 -21.912657 -14.950195 -18.955961 -21.585274 -20.170464 -15.718303        NaN        NaN      NaN          NaN
3   Africa Western and Central          AFW  Current account balance (% of GDP)  BN.CAB.XOKA.GD.ZS   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN       NaN       NaN       NaN        NaN        NaN       NaN        NaN       NaN       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN       NaN        NaN        NaN        NaN        NaN       NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN      NaN          NaN
4                       Angola          AGO  Current account balance (% of GDP)  BN.CAB.XOKA.GD.ZS   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN       NaN       NaN       NaN        NaN        NaN       NaN -11.369048 -7.666922 -5.327049  49.979325 -11.511286 -28.696878 -27.798331   8.715064 -16.012951  -0.981927 -4.039582   2.892476  13.897099  20.407808  16.212397  8.125543 -10.769384   8.957042  11.704684  10.808957   6.154696  -2.756200 -11.351656  -5.847424  -0.858822   9.317234   7.246181   1.797711  12.629780  11.267153  4.96921          NaN

In [4]:
# Filter for 'Sweden' in 'Country Name' column
sweden_data1 = data1[data1['Country Name'] == 'Sweden']
sweden_data2 = data2[data2['Country Name'] == 'Sweden']
sweden_data3 = data3[data3['Country Name'] == 'Sweden']
sweden_data4 = data4[data4['Country Name'] == 'Sweden']

In [5]:
len(sweden_data4.columns)

69

In [6]:
# Keep only the year columns and indicator values and transposing to get year-wise columns
sweden_data1_cleaned = sweden_data1.drop(columns=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', 'Unnamed: 68']).T
sweden_data2_cleaned = sweden_data2.drop(columns=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', 'Unnamed: 68']).T
sweden_data3_cleaned = sweden_data3.drop(columns=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', 'Unnamed: 68']).T
sweden_data4_cleaned = sweden_data4.drop(columns=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', 'Unnamed: 68']).T

In [7]:
sweden_data2_cleaned.head()

sweden_data2_cleaned.shape

(64, 1)

In [8]:
# Rename the columns for clarity
sweden_data1_cleaned.columns = ['Current Account Balance (% of GDP)']
sweden_data2_cleaned.columns = ['Inflation (CPI)']
sweden_data3_cleaned.columns = ['GDP (current US$)']
sweden_data4_cleaned.columns = ['Unemployment (% of Labor Force)']

# Combine the datasets into a single DataFrame
combined_data = pd.concat([sweden_data1_cleaned, sweden_data2_cleaned, sweden_data3_cleaned, sweden_data4_cleaned], axis=1)

In [9]:
# Set the index as 'Year'
combined_data.index.name = 'Year'

# Reset index to make 'Year' a column
combined_data.reset_index(inplace=True)

In [10]:
# Save the combined data to a new CSV file
output_file_path = 'Sweden_data.csv'
combined_data.to_csv(output_file_path, index=False)